version: "3.7"
services:
  pwa:
    image: node:14.18.1

    tty: true

    volumes:
      - ./app/:/app

    ports:
      - 10000:10000

    networks:
      - magento
networks:
  magento:
    name: magento_network
    driver: bridge
