module.exports = componentOverrideMapping = {
  //JS
  [`@magento/venia-ui/lib/components/Button/button.js`]: './src/components/Button/button.js',
  [`@magento/venia-ui/lib/components/Checkbox/checkbox.js`]: './src/components/Checkbox/checkbox.js',
  [`@magento/venia-ui/lib/components/Select/select.js`]: './src/components/Select/select.js',
  [`@magento/venia-ui/lib/components/TextInput/textInput.js`]: './src/components/TextInput/textInput.js',
  [`@magento/venia-ui/lib/components/RadioGroup/radio.js`]: './src/components/RadioGroup/radio.js',
  [`@magento/venia-ui/lib/components/Logo/logo.js`]: './src/components/Logo/logo.js',
  [`@magento/venia-ui/lib/components/SignIn/signIn.js`]: './src/components/SignIn/signIn.js',
  [`@magento/venia-ui/lib/components/ErrorView/errorView.js`]: './src/components/ErrorView/errorView.js',
  [`@magento/venia-ui/lib/components/Footer/sampleData.js`]: './src/components/Footer/sampleData.js',
  //[`@magento/venia-ui/lib/components/ProductImageCarousel/carousel.js`]: './src/components/ProductImageCarousel/carousel.js',
  //[`@magento/venia-ui/lib/components/ProductOptions/options.js`]: './src/components/ProductOptions/options.js',
  [`@magento/venia-ui/lib/components/Header/searchTrigger.js`]: './src/components/Header/searchTrigger.js',
  [`@magento/venia-ui/lib/components/AccountChip/accountChip.js`]: './src/components/AccountChip/accountChip.js',
  //[`@magento/venia-ui/lib/components/Header/cartTrigger.js`]: './src/components/Header/cartTrigger.js',
  //[`@magento/venia-ui/lib/components/ProductSort/productSort.js`]: './src/components/ProductSort/productSort.js',
  [`@magento/venia-ui/lib/components/OrderHistoryPage/collapsedImageGallery.js`]: './src/components/OrderHistoryPage/collapsedImageGallery.js',
  [`@magento/venia-ui/lib/components/SearchBar/suggestedProduct.js`]: './src/components/SearchBar/suggestedProduct.js',
  [`@magento/venia-ui/lib/components/SearchBar/autocomplete.js`]: './src/components/SearchBar/autocomplete.js',
  //[`@magento/venia-ui/lib/components/Price/price.js`]: './src/components/Price/price.js',
  //[`@magento/venia-ui/lib/components/ProductFullDetail/productFullDetail.js`]: './src/components/ProductFullDetail/productFullDetail.js',
  //[`@magento/venia-ui/lib/components/Gallery/item.js`]: './src/components/Gallery/item.js',
  //[`@magento/venia-ui/lib/components/Gallery/gallery.js`]: './src/components/Gallery/gallery.js',
  [`@magento/venia-ui/lib/components/WishlistPage/wishlistItem.js`]: './src/components/WishlistPage/wishlistItem.js',
  //[`@magento/venia-ui/lib/components/MegaMenu/megaMenu.js`]: './src/components/MegaMenu/megaMenu.js',
  [`@magento/venia-ui/lib/components/AddToCartDialog/addToCartDialog.js`]: './src/components/AddToCartDialog/addToCartDialog.js',
  //[`@magento/venia-ui/lib/components/App/contextProvider.js`]: './src/components/App/contextProvider.js',
  //[`@magento/venia-ui/lib/RootComponents/Category/categoryContent.js`]: './src/RootComponents/Category/categoryContent.js',
  [`@magento/venia-ui/lib/components/CartPage/ProductListing/product.js`]: './src/components/CartPage/ProductListing/product.js',
  [`@magento/venia-ui/lib/components/CartPage/ProductListing/productListing.js`]: './src/components/CartPage/ProductListing/productListing.js',
  [`@magento/venia-ui/lib/components/CartPage/PriceSummary/priceSummary.js`]: './src/components/CartPage/PriceSummary/priceSummary.js',
  [`@magento/venia-ui/lib/components/CartPage/cartPage.js`]: './src/components/CartPage/cartPage.js',

  //TALONS
 /* [`@magento/peregrine/lib/talons/ProductFullDetail/useProductFullDetail.js`]: './src/talons/ProductFullDetail/useProductFullDetail.js',
  [`@magento/peregrine/lib/talons/WishlistPage/useWishlistItem.js`]: './src/talons/WishlistPage/useWishlistItem.js',
  [`@magento/peregrine/lib/talons/OrderHistoryPage/useOrderHistoryPage.js`]: './src/talons/OrderHistoryPage/useOrderHistoryPage.js',
  [`@magento/peregrine/lib/talons/OrderHistoryPage/useOrderRow.js`]: './src/talons/OrderHistoryPage/useOrderRow.js',
  [`@magento/peregrine/lib/talons/CartPage/PriceSummary/usePriceSummary.js`]: './src/talons/usePriceSummary.js',

  //GRAPHQL
  [`@magento/peregrine/lib/talons/WishlistPage/wishlistItemFragments.gql.js`]: './src/talons/WishlistPage/wishlistItemFragments.gql.js',
  [`@magento/peregrine/lib/talons/MegaMenu/megaMenu.gql.js`]: './src/talons/MegaMenu/megaMenu.gql.js',
  [`@magento/peregrine/lib/talons/SearchPage/searchPage.gql.js`]: './src/talons/SearchPage/searchPage.gql.js',
  [`@magento/peregrine/lib/talons/RootComponents/Product/productDetailFragment.gql.js`]: './src/talons/RootComponents/Product/productDetailFragment.gql.js',
  [`@magento/peregrine/lib/talons/RootComponents/Category/categoryFragments.gql.js`]: './src/talons/RootComponents/Category/categoryFragments.gql.js',*/

  //CSS
    /*[`@magento/venia-ui/lib/index.module.css`]: './src/css/index.module.css',
    [`@magento/venia-ui/lib/tokens.module.css`]: './src/css/tokens.module.css',
    [`@magento/venia-ui/lib/components/Button/button.module.css`]: './src/components/Button/button.module.css',
    [`@magento/venia-ui/lib/components/Field/field.module.css`]: './src/components/Field/field.module.css',
    [`@magento/venia-ui/lib/components/RadioGroup/radio.module.css`]: './src/components/RadioGroup/radio.module.css',
    [`@magento/venia-ui/lib/components/Select/select.module.css`]: './src/components/Select/select.module.css',
    [`@magento/venia-ui/lib/components/LinkButton/linkButton.module.css`]: './src/components/LinkButton/linkButton.module.css',
    [`@magento/venia-ui/lib/components/Checkbox/checkbox.module.css`]: './src/components/Checkbox/checkbox.module.css',
    [`@magento/venia-ui/lib/components/AccountInformationPage/accountInformationPage.module.css`]: './src/components/AccountInformationPage/accountInformationPage.module.css',
    [`@magento/venia-ui/lib/components/Dialog/dialog.module.css`]: './src/components/Dialog/dialog.module.css',
    [`@magento/venia-ui/lib/components/AddressBookPage/addressBookPage.module.css`]: './src/components/AddressBookPage/addressBookPage.module.css',
    [`@magento/venia-ui/lib/components/AddressBookPage/addressCard.module.css`]: './src/components/AddressBookPage/addressCard.module.css',
    [`@magento/venia-ui/lib/components/MiniCart/miniCart.module.css`]: './src/components/MiniCart/miniCart.module.css',
    [`@magento/venia-ui/lib/components/CartPage/PriceAdjustments/ShippingMethods/shippingMethods.module.css`]: './src/components/CartPage/PriceAdjustments/ShippingMethods/shippingMethods.module.css',
    [`@magento/venia-ui/lib/components/CartPage/PriceAdjustments/ShippingMethods/shippingForm.module.css`]: './src/components/CartPage/PriceAdjustments/ShippingMethods/shippingForm.module.css',
    //[`@magento/venia-ui/lib/components/CartPage/PriceAdjustments/GiftOptions/giftOptions.module.css`]: './src/components/CartPage/PriceAdjustments/GiftOptions/giftOptions.module.css',
    [`@magento/venia-ui/lib/components/Header/accountTrigger.module.css`]: './src/components/Header/accountTrigger.module.css',
    [`@magento/venia-ui/lib/components/Header/header.module.css`]: './src/components/Header/header.module.css',
    [`@magento/venia-ui/lib/components/OrderHistoryPage/orderHistoryPage.module.css`]: './src/components/OrderHistoryPage/orderHistoryPage.module.css',
    [`@magento/venia-ui/lib/components/OrderHistoryPage/orderProgressBar.module.css`]: './src/components/OrderHistoryPage/orderProgressBar.module.css',
    [`@magento/venia-ui/lib/components/MegaMenu/submenu.module.css`]: './src/components/MegaMenu/submenu.module.css',
    [`@magento/venia-ui/lib/components/MegaMenu/megaMenu.module.css`]: './src/components/MegaMenu/megaMenu.module.css',
    [`@magento/venia-ui/lib/components/ProductSort/productSort.module.css`]: './src/components/ProductSort/productSort.module.css',
    [`@magento/venia-ui/lib/components/FilterModal/filterModal.module.css`]: './src/components/FilterModal/filterModal.module.css',
    [`@magento/venia-ui/lib/components/CheckoutPage/checkoutPage.module.css`]: './src/components/CheckoutPage/checkoutPage.module.css',
    [`@magento/venia-ui/lib/components/CheckoutPage/ShippingInformation/shippingInformation.module.css`]: './src/components/CheckoutPage/ShippingInformation/shippingInformation.module.css',
    [`@magento/venia-ui/lib/components/CheckoutPage/ShippingInformation/AddressForm/customerForm.module.css`]: './src/components/CheckoutPage/ShippingInformation/AddressForm/customerForm.module.css',
    [`@magento/venia-ui/lib/components/CheckoutPage/ShippingMethod/completedView.module.css`]: './src/components/CheckoutPage/ShippingMethod/completedView.module.css',
    [`@magento/venia-ui/lib/components/CheckoutPage/AddressBook/addressBook.module.css`]: './src/components/CheckoutPage/AddressBook/addressBook.module.css',
    [`@magento/venia-ui/lib/components/CheckoutPage/AddressBook/addressCard.module.css`]: './src/components/CheckoutPage/AddressBook/addressCard.module.css',
    [`@magento/venia-ui/lib/components/LoadingIndicator/indicator.module.css`]: './src/components/LoadingIndicator/indicator.module.css',
    [`@magento/venia-ui/lib/RootComponents/Category/category.module.css`]: './src/RootComponents/Category/category.module.css',
    [`@magento/venia-ui/lib/components/MyAccount/ResetPassword/resetPassword.module.css`]: './src/components/MyAccount/ResetPassword/resetPassword.module.css',
    [`@magento/venia-ui/lib/components/ProductImageCarousel/carousel.module.css`]: './src/components/ProductImageCarousel/carousel.module.css',
    [`@magento/venia-ui/lib/components/ProductImageCarousel/thumbnail.module.css`]: './src/components/ProductImageCarousel/thumbnail.module.css',
    [`@magento/venia-ui/lib/components/ProductOptions/tileList.module.css`]: './src/components/ProductOptions/tileList.module.css',
    [`@magento/venia-ui/lib/components/ProductOptions/tile.module.css`]: './src/components/ProductOptions/tile.module.css',
    [`@magento/venia-ui/lib/components/FilterModalOpenButton/filterModalOpenButton.module.css`]: './src/components/FilterModalOpenButton/filterModalOpenButton.module.css',
    [`@magento/venia-ui/lib/components/Wishlist/AddToListButton/addToListButton.module.css`]: './src/components/Wishlist/AddToListButton/addToListButton.module.css',
    [`@magento/venia-ui/lib/components/Wishlist/WishlistDialog/wishlistDialog.module.css`]: './src/components/Wishlist/WishlistDialog/wishlistDialog.module.css',
    [`@magento/venia-ui/lib/components/Wishlist/WishlistDialog/CreateWishlistForm/createWishlistForm.module.css`]: './src/components/Wishlist/WishlistDialog/CreateWishlistForm/createWishlistForm.module.css',
    [`@magento/venia-ui/lib/components/Wishlist/WishlistDialog/WishlistLineItem/wishlistLineItem.module.css`]: './src/components/Wishlist/WishlistDialog/WishlistLineItem/wishlistLineItem.module.css',
    [`@magento/venia-ui/lib/components/WishlistPage/wishlist.module.css`]: './src/components/WishlistPage/wishlist.module.css',
    [`@magento/venia-ui/lib/components/WishlistPage/createWishlist.module.css`]: './src/components/WishlistPage/createWishlist.module.css',
    [`@magento/venia-ui/lib/components/WishlistPage/wishlistConfirmRemoveProductDialog.module.css`]: './src/components/WishlistPage/wishlistConfirmRemoveProductDialog.module.css',
    [`@magento/venia-ui/lib/components/WishlistPage/wishlistEditFavoritesListDialog.module.css`]: './src/components/WishlistPage/wishlistEditFavoritesListDialog.module.css',
    [`@magento/venia-ui/lib/components/WishlistPage/wishlistItem.module.css`]: './src/components/WishlistPage/wishlistItem.module.css',
    [`@magento/venia-ui/lib/components/WishlistPage/wishlistItems.module.css`]: './src/components/WishlistPage/wishlistItems.module.css',
    [`@magento/venia-ui/lib/components/WishlistPage/wishlistMoreActionsDialog.module.css`]: './src/components/WishlistPage/wishlistMoreActionsDialog.module.css',
    [`@magento/venia-ui/lib/components/WishlistPage/wishlistPage.module.css`]: './src/components/WishlistPage/wishlistPage.module.css',
    [`@magento/venia-ui/lib/components/PageLoadingIndicator/pageLoadingIndicator.module.css`]: './src/components/PageLoadingIndicator/pageLoadingIndicator.module.css',
    [`@magento/venia-ui/lib/components/SearchPage/searchPage.module.css`]: './src/components/SearchPage/searchPage.module.css',
    [`@magento/venia-ui/lib/components/Accordion/section.module.css`]: './src/components/Accordion/section.module.css',
    [`@magento/venia-ui/lib/components/LegacyMiniCart/section.module.css`]: './src/components/LegacyMiniCart/section.module.css',
    [`@magento/venia-ui/lib/components/CartPage/ProductListing/product.module.css`]: './src/components/CartPage/ProductListing/product.module.css',
    [`@magento/venia-ui/lib/components/OrderHistoryPage/orderRow.module.css`]: './src/components/OrderHistoryPage/orderRow.module.css',
    [`@magento/venia-ui/lib/components/CartPage/cartPage.module.css`]: './src/components/CartPage/cartPage.module.css',
    [`@magento/venia-ui/lib/components/CartPage/PriceSummary/priceSummary.module.css`]: './src/components/CartPage/PriceSummary/priceSummary.module.css',*/
    
  //Orienteed components
  ////JS
  [`@orienteed/buyLaterNotes/components/SavedCarts/savedCartsTable.js`]: './src/components/SavedCarts/savedCartsTable.js',
  ////CSS
  [`@orienteed/reorder/components/ReOrderBtn/reOrderBtn.module.css`]: './src/components/ReOrderBtn/reOrderBtn.module.css',
  [`@orienteed/customComponents/css/forms.module.css`]: './src/css/forms.module.css',


  /* PRODUCT FULL DETAIL B2B
  //JS
  [`@magento/venia-ui/lib/components/CartPage/ProductListing/quantity.js`]: './src/components/ProductListing/quantity.js',
  [`@magento/venia-ui/lib/components/ProductFullDetail/productFullDetail.js`]: './src/components/ProductFullDetail/productFullDetail.js',

  //TALONS
  [`@magento/peregrine/lib/talons/CartPage/ProductListing/useQuantity.js`]: './src/talons/ProductListing/useQuantity.js',
  [`@magento/peregrine/lib/talons/ProductFullDetail/useProductFullDetail.js`]: './src/talons/ProductFullDetail/useProductFullDetail.js',
  */
};
